// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL6K1Zbjg8qNYFOZPOLoEmPJS3uoI4NIA',
    appId: '1:208759947479:android:0c30d6eee66c3f3723b092',
    messagingSenderId: '208759947479',
    projectId: 'pawhealth-app-2026',
    storageBucket: 'pawhealth-app-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi8C9sobjIepsuyrKitdVyfuKILPB-dYg',
    appId: '1:208759947479:ios:d611a81436f0698323b092',
    messagingSenderId: '208759947479',
    projectId: 'pawhealth-app-2026',
    storageBucket: 'pawhealth-app-2026.firebasestorage.app',
    iosBundleId: 'com.pawhealth.pawhealth',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDuNmSXnzp1ADDEismJ1yMB5NpjNAmc8M',
    appId: '1:208759947479:web:46cdc02f7b5d897923b092',
    messagingSenderId: '208759947479',
    projectId: 'pawhealth-app-2026',
    authDomain: 'pawhealth-app-2026.firebaseapp.com',
    storageBucket: 'pawhealth-app-2026.firebasestorage.app',
  );
}
